import Header from "@/components/Header";
import NavBar from "@/components/NavBar";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Header />
				<NavBar />
				{children}
			</body>
		</html>
	);
}
