import Header from "@/components/Header";
import "./globals.css";
// import { Creepster } from "../app/fonts";

// const creep = Creepster({
// 	subsets: ["latin"],
// 	weight: "400",
// 	display: "swap",
// 	variable: "--font-creep",
// });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Header />
				{children}
			</body>
		</html>
	);
}
